events { worker_connections 1024; }

http {
    upstream migraine_app_servers {
        # Овде Jenkins ќе ја менува адресата со 'sed' командата
        # На почеток стави ја Green верзијата како активна
        server host.docker.internal:5052; 
    }

    server {
        listen 80;

        location / {
            proxy_pass http://migraine_app_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}